### ISSUE TITLE
Problem to simulate the models

### ISSUE THREAD

**Issue by fellipegm** [MathWorks-Teaching-Resources/Virtual-Controls-Laboratory#1]
I have problems when I try to run the models on MATLAB Online. Please find the error attached.

The models does not compile and I always have problems with some Simscape parameters. The error for the VirtualVehicle is as follows:

Error:['VirtualVehicle']: The following errors were found in the model VirtualVehicle.
Caused by:
    ['VirtualVehicle/Vehicle and road/Animation/Body']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Body']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Seats']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Seats']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FL/hub']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FL/hub']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FL/rim']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FL/rim']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FL/wheel']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FL/wheel']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FR/hub']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FR/hub']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FR/rim']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FR/rim']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FR/wheel']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel FR/wheel']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RL/hub']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RL/hub']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RL/rim']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RL/rim']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RL/wheel']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RL/wheel']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RR/hub']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RR/hub']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RR/rim']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RR/rim']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RR/wheel']: The parameter Geometry/File Name is a file that does not exist. Resolve this issue in order to simulate the model.
    ['VirtualVehicle/Vehicle and road/Animation/Wheel RR/wheel']: Inertia cannot be computed from geometry. Resolve this issue in order to simulate the model.

![firefox_JDoCEqSdd7](https://github.com/MathWorks-Teaching-Resources/Virtual-Controls-Laboratory/assets/29079463/b4297f42-e8d8-4ff9-a91e-05b5700684bf)

**Comment by Altantsooj** [comment]
Same problem here. How to solve it?

**Comment by callieEDU** [comment]
Hi @fellipegm and @Altantsooj,

The issue you mentioned has now been updated and fixed with a new version release. You can access the update on Github or file exchange. Thank you for flagging!
